config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossips do
    resources :comments
  end
   resources :author
   resources :cities
   resources :sessions, only: [:new, :create, :destroy]

   root 'gossips#index'
   get '/static_pages/team', to: 'static_pages#team', as: 'team'
   get '/static_pages/contact', to: 'static_pages#contact', as: 'contact'
   get '/welcome/:index', to: 'welcome#index'
   get '/dashboards/profil', to: 'dashboards#profil'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	#je fais ma relation qu'une city peut avoir plusieur users
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #je fais mes conditions
  validates :content,  presence: { message: "Le commentaire doit être renseigné"}

  #un commentaire peut avoir qu'un seul auteur et être sur un seul gossip
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

	# un gossip peut avoir plusieur commentaires
	has_many :comments

#Validation titre
	validates :title, presence: { message: "Le titre doit être renseigné"}

  validates :title, length: {minimum: 3, maximum: 14, message: "le titre doit etre compris entre 3 et 14 caracteres"}

	validates :title, uniqueness: { message: "Ce titre est déjà pris."}



#Validation contenu

validates :content, presence: { message: "le contenu doit être renseigné."}
validates :content, length: {minimum: 20, message: "Le contenu doit faire au moins 20 caracteres"}


end

app/models/message_prive.rb
class MessagePrive < ApplicationRecord
	#je permet une relation sender et recipient avec la class user
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	#cette relation: un tag peut avoir plusieur gossip
	has_many :tagGossips
	has_many :Gossips, through: :tagGossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	#cette relation intermédiaire me permet de faire le lien entre gossip et tag
	belongs_to :gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	#j'effectue ma relation: 1 utilisateur appartient à 1 ville
	belongs_to :city
	#l'utilisateur peut avoir écrit plusieur gossips
	has_many :gossips
	#qu'un user peut envoyer plusieur message et recevoir plusieur message
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "MessagePrive"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "MessagePrive"
	#un user peut écrire plusieur commentaires
	has_many :comments
	
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	validates :first_name, presence: {message: "Le prenom doit être renseigné !"}
	validates :last_name, presence:  {message: "Le nom doit être renseigné !"}
	validates :description, presence: {message: "La description doit être renseigné !"}
	validates :email, uniqueness: {message: "l'email est deja pris !"}
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "L'email doit être renseigné au bon format (email@eamil.email) !"}
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:show,:new,:create,:edit,:update,:destroy]
  def index
    @gossip = Gossip.all
    @user = User.all
    @first_name = session[:first_name]
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.all
    @city = City.all
    @comment = Comment.all
  end

  def new
    @gossip = current_user
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    @gossip = Gossip.new(user_id: session[:user_id], title: params[:title], content: params[:content]) # avec xxx qui sont les données obtenues à partir du formulaire

    if @gossip.save # essaie de sauvegarder en base @gossip
      flash[:success] = "Le gossip a bien été répendu"
      redirect_to gossips_path
        else
      flash.now[:danger] = "Erreur, Gossip non crée"
      render 'gossips/new'# sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    @gossip = Gossip.find(params[:id])
  #j'applique la modif à moins que compare_user est faux (voir applicationController)
    unless compare_user(session[:user_id], @gossip.user_id) == false
      if @gossip.update(title: params[:title], content: params[:content])
        flash[:success] = "Le gossip a bien été modifié"
        redirect_to gossip_path(@gossip)
      else
        flash.now[:danger] = "Le gossip n'a pas été modifié"
        render :edit
      end
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    unless compare_user(session[:user_id], @gossip.user_id) == false
      if @gossip.destroy
        flash[:success] = "Le gossip a été supprimé"
          redirect_to gossips_path
      else
        render :show
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_page_helper.rb
module ContactPageHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_page_helper.rb
module TeamPageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>
<body style="color:white;">
  <center>
<% if @gossip.errors.any? %>
      <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li style="color:red;"><%= message %></li>
        <% end %>
      </ul>
    <%else flash[:success] %>
<% end %>

<br>
<br>
<p> Modifie ton gossip </p>
<%= form_tag  url_for(action: 'update'), method: "patch" do %>

  <%= label_tag 'Title' %>
  <%= text_field_tag 'title', @gossip.title %>
  <br /> <br />

  <%= label_tag 'Contenu' %>
  <%= text_area_tag 'content', @gossip.content %>
  <br /> <br />

  <%= submit_tag "Modifier le Post" %>

<% end %>
</center>
</body>

app/views/gossips/index.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>



<% if flash.now[:danger] %>
<div class="alert alert-danger" role="alert">
<div class="danger"><%= flash.now[:danger]%></div>
<% end %>

<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <% if flash[:success] %>
   <div class="alert alert-success" role="alert">
   <div class="success"><%= flash[:success]%></div>
   </div>
 <% end %>

    <h1 class="display-4 text-white">Bienvenue <%= @first_name%> sur le site des meilleurs Gossip !</h1>
    <h4 class="lead text-white">Ici tu trouvera les secrets les plus profond...</h4>
  </div>
</div>
<body>
  <center>

<p> Toi aussi tu veux creer un Gossip ? C'est <a href="<%= new_gossip_path %>">là</a> !</p>
  </center>
<br>
<div class="container mx-auto">
<div class="card-columns">
<% @gossip.each do |t| %>
    <div class="card card p-3 shadow" style="width: 18rem;">
      <img class="card-img-top" src="https://is3-ssl.mzstatic.com/image/thumb/Podcasts113/v4/dc/27/a1/dc27a1eb-2307-fe47-342e-6fb84618f5a8/mza_8792713575073991728.jpg/600x600bb.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title text-center"><%= t.title %></h5>
        <p class="card-text"><%= t.content %></p>
        <p class="card-text text-muted">Posted by <%=link_to @user.find(t.user_id).first_name, author_path(t.user_id)%></p>
        <a class="btn btn-outline-success" href="<%= gossip_path(t) %>">Voir plus</a>
      </div>
    </div>
<% end %>
  </div>
  </div>
<br><br>
</body>

app/views/gossips/new.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
<center>
    <!-- ... -->
<br/><br/>
<% if @gossip.errors.any? %>
      <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li style="color:red;"><%= message %></li>
        <% end %>
      </ul>
<% end %>

<p> Creer ton gossip </p>
    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title' %>
      <br /> <br />

      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'content' %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

    <% end %>

    <!-- ... -->
</center>
</body>

app/views/gossips/show.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
  <br><br>
  <center>   <% if flash[:success] %>
   <div class="alert alert-success" role="alert">
   <div class="success"><%= flash[:success]%></div>
   </div>
  <% end %>
  <% h = @gossip.user_id %>
    <div class="card text-center mx-auto" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @gossip.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%=@gossip.created_at.strftime("%d/%m/%Y") %></h6>
        <h6 class="card-subtitle mb-2 text-muted">modifié le: <%=@gossip.updated_at.strftime("%d/%m/%Y")%></h6>
        <h6 class="card-subtitle mb-2 text-muted"><%= link_to @user.find(@gossip.user_id).first_name ,author_path(@gossip.user_id)%></h6>
        <p class="card-text"><%= @gossip.content %></p>
        <p class="card-text"> ville : <%=link_to "#{@city.find(@user.find(@gossip.user_id).city_id).name}", city_path(@user.find(@gossip.user_id).city_id) %></p>
        <% if current_user && (session[:user_id] == @gossip.user_id) %>
        <a class="btn btn-outline-danger" href="<%= edit_gossip_path %>">Modifier le gossip</a>
        <br/><br/>
        <%= form_tag url_for(action: 'destroy'), method: "DELETE" do %>

           <%= submit_tag "Supprimer le gossip" %>
<br><br>
       <% end %>
       <%end%>
       <%= link_to "Commenter", new_gossip_comment_path(@gossip.id), class: "btn btn-primary" %>
       <br /><br />

       <p>Commentaires du potin :</p>
         <% @gossip.comments.each do |comment| %>
             <div class="card">
               <div class="card-body">
                 <h6 class="card-subtitle mb-2 text-muted">Auteur : <%= link_to comment.user.first_name, author_path(comment.user.id) %></h6>
                 <p class="card-text"><%= comment.content %></p>
                <% if current_user && (session[:user_id] == comment.user_id) %>
                 <%= link_to "Modifier le commentaire", edit_gossip_comment_path(comment.id), class: "btn btn-success" %>

                 <%# link_to "Supprimer", gossip_comment_path(params), method: :delete, class: "btn btn-danger" %>


               <% end %>

               </div>
             </div>
         <% end %>
      </div>
    </div>
  </center>
</body>