config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossips do
    resources :comments
  end
   resources :author
   resources :cities
   resources :sessions, only: [:new, :create, :destroy]

   root 'gossips#index'
   get '/static_pages/team', to: 'static_pages#team', as: 'team'
   get '/static_pages/contact', to: 'static_pages#contact', as: 'contact'
   get '/welcome/:index', to: 'welcome#index'
   get '/dashboards/profil', to: 'dashboards#profil'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	#je fais ma relation qu'une city peut avoir plusieur users
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #je fais mes conditions
  validates :content,  presence: { message: "Le commentaire doit être renseigné"}

  #un commentaire peut avoir qu'un seul auteur et être sur un seul gossip
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

	# un gossip peut avoir plusieur commentaires
	has_many :comments

#Validation titre
	validates :title, presence: { message: "Le titre doit être renseigné"}

  validates :title, length: {minimum: 3, maximum: 14, message: "le titre doit etre compris entre 3 et 14 caracteres"}

	validates :title, uniqueness: { message: "Ce titre est déjà pris."}



#Validation contenu

validates :content, presence: { message: "le contenu doit être renseigné."}
validates :content, length: {minimum: 20, message: "Le contenu doit faire au moins 20 caracteres"}


end

app/models/message_prive.rb
class MessagePrive < ApplicationRecord
	#je permet une relation sender et recipient avec la class user
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	#cette relation: un tag peut avoir plusieur gossip
	has_many :tagGossips
	has_many :Gossips, through: :tagGossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	#cette relation intermédiaire me permet de faire le lien entre gossip et tag
	belongs_to :gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	#j'effectue ma relation: 1 utilisateur appartient à 1 ville
	belongs_to :city
	#l'utilisateur peut avoir écrit plusieur gossips
	has_many :gossips
	#qu'un user peut envoyer plusieur message et recevoir plusieur message
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "MessagePrive"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "MessagePrive"
	#un user peut écrire plusieur commentaires
	has_many :comments
	
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	validates :first_name, presence: {message: "Le prenom doit être renseigné !"}
	validates :last_name, presence:  {message: "Le nom doit être renseigné !"}
	validates :description, presence: {message: "La description doit être renseigné !"}
	validates :email, uniqueness: {message: "l'email est deja pris !"}
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "L'email doit être renseigné au bon format (email@eamil.email) !"}
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController

  def index

  end

  def show
    @user = User.find(params[:id])
    @city = City.all
    @gossips = Gossip.all
    @gossip = User.find(params[:id])
  end

  def new
    @user_create = User.new
  end

  def create
      nb = rand(1..10)
      @user_create = User.new(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], city_id: nb, email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation], description: params[:description])
      if @user_create.save
        log_in(@user_create)
      flash[:success] = "Votre profil a bien été crée"
        redirect_to author_path(session[:user_id])
      else
      flash.now[:danger] = "Votre profil n'a pas été crée"
        render :new
      end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
  #j'applique la modif à moins que compare_user est faux (voir applicationController)
    unless compare_user(session[params[:user_id]], params[:user_id]) == false
      if @user.update(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], description: params[:description], password: :password_confirmation)
        flash[:success] = "Votre profil a bien été modifié"
        redirect_to author_path(session[:user_id])
      else
      flash.now[:danger] = "Votre profil n'a pas été modifié"
        render :edit
      end
    end
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_page_helper.rb
module ContactPageHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/team_page_helper.rb
module TeamPageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/author/edit.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
<center>
<br/> <br/>
<h1> Modifie ton profil </h1>
<br/>
<% if @user.errors.any? %>
      <p>Nous n'avons pas réussi à modifier votre profil pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li style="color:red;"><%= message %></li>
        <% end %>
      </ul>
<% else flash[:success] %>
<% end %>


<%= form_tag url_for(action: 'update'), method: "patch" do %>

  <%= label_tag 'Prenom' %>
  <%= text_field_tag 'first_name', @user.first_name %>
  <br /> <br />

  <%= label_tag 'Nom' %>
  <%= text_field_tag 'last_name', @user.last_name %>
  <br /> <br />

  <%= label_tag 'Age' %>
  <%= text_field_tag 'age', @user.age %>
  <br /> <br />

  <%= label_tag 'Description' %>
  <%= text_area_tag 'description', @user.description %>
  <br /> <br />

  <%= submit_tag "Modifier profil" %>

<% end %>
</center>
</body>

app/views/author/new.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
<center>
<br/> <br/>
<h1> Rejoins la communauté des ragots infondés </h1>
<br/>

<% if @user_create.errors.any? %>
      <p>Nous n'avons pas réussi à créer votre profil pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @user_create.errors.full_messages.each do |message| %>
          <li style="color:red;"><%= message %></li>
        <% end %>
      </ul>
<% else flash[:success] %>
<% end %>

<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag 'Prenom' %>
  <%= text_field_tag 'first_name' %>
  <br /> <br />

  <%= label_tag 'Nom' %>
  <%= text_field_tag 'last_name' %>
  <br /> <br />

  <%= label_tag 'Age' %>
  <%= text_field_tag 'age' %>
  <br /> <br />

  <%= label_tag 'Email' %>
  <%= text_field_tag 'email' %>
  <br /> <br />

  <%= label_tag 'Description' %>
  <%= text_area_tag 'description' %>
  <br /> <br />

  <%= label_tag 'Password' %>
  <%= password_field_tag 'password', nil, class: 'masked_input_field'%>
  <br /> <br />

  <%= label_tag 'Confirm Password' %>
  <%= password_field_tag 'password_confirmation', nil, class: 'masked_input_field'%>
  <br /> <br />

  <%= submit_tag "M'inscrire" %>

<% end %>
</center>
</body>

app/views/author/show.html.erb
<style>
body
{background-image: url('http://4everstatic.com/images/abstrait/fond-de-couleur-220805.jpg');
   background-repeat: no-repeat;
   background-size:cover;
   background-attachment:fixed;}
</style>

<body>
<center>
  <% if flash[:success] %>
 <div class="alert alert-success" role="alert">
 <div class="success"><%= flash[:success]%></div>
 </div>
<% end %>
<br><br>
<div class="card card p-3 shadow" style="width: 18rem;">
  <img class="card-img-top" src="https://img.huffingtonpost.com/asset/5da6cd98210000140f34a123.jpeg?cache=kQdUrib9K7&ops=scalefit_630_noupscale" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
    <p class="card-text">Description : <%= @user.description %></p>
    <p class="card-text">Age : <%= @user.age %> </p>
    <p class="card-text">email : <%= @user.email %></p>
    <a class="" href="<%= city_path(@user.city_id) %>">City : <%= @city.find(@user.city_id).name %> </a>

    <% if current_user && (session[:user_id] == @user.id) %>
    <a class="btn btn-outline-danger" href="<%= edit_author_path %>"> Modifie ton profil </a>
    <% end %>
    <br/><br/>
    <h3 class="text-center">Mes gossips</h3>
  </div>
</div>
    <% a = @gossips.where(user_id: params[:id]) %>
    <div class="container mx-auto">
    <div class="card-columns">
    <% a.each do |t|%>
        <div class="card card p-3 shadow" style="width: 18rem;"">
          <img class="card-img-top" src="https://is3-ssl.mzstatic.com/image/thumb/Podcasts113/v4/dc/27/a1/dc27a1eb-2307-fe47-342e-6fb84618f5a8/mza_8792713575073991728.jpg/600x600bb.jpg" alt="Card image cap">

          <div class="card-body">
            <h5 class="card-title text-center"><%=t.title%></h5>
            <p class="card-text text-center"><%= t.content %></p>
            <% if current_user.id == @user.id %>
            <a class="btn btn-outline-danger pull-left" href="<%= edit_gossip_path %>">Modifier</a>
            <a href="<%= gossip_path(t) %>" class="btn btn-danger clearfix" data-confirm="Êtes vous sûr de vouloir supprimer ce gossip?" data-method="DELETE">Supprimer</a>
           <% end %>
           <br/> <br>
           <a class="btn btn-outline-success pull-right" href="<%= gossip_path(t) %>">Voir la suite..</a>
          </div>
        </div>
    <% end %>
        <br><br>
</body>