config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossips do
    resources :comments
  end
   resources :author
   resources :cities
   resources :sessions, only: [:new, :create, :destroy]

   root 'gossips#index'
   get '/static_pages/team', to: 'static_pages#team', as: 'team'
   get '/static_pages/contact', to: 'static_pages#contact', as: 'contact'
   get '/welcome/:index', to: 'welcome#index'
   get '/dashboards/profil', to: 'dashboards#profil'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	#je fais ma relation qu'une city peut avoir plusieur users
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #je fais mes conditions
  validates :content,  presence: { message: "Le commentaire doit être renseigné"}

  #un commentaire peut avoir qu'un seul auteur et être sur un seul gossip
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

	# un gossip peut avoir plusieur commentaires
	has_many :comments

#Validation titre
	validates :title, presence: { message: "Le titre doit être renseigné"}

  validates :title, length: {minimum: 3, maximum: 14, message: "le titre doit etre compris entre 3 et 14 caracteres"}

	validates :title, uniqueness: { message: "Ce titre est déjà pris."}



#Validation contenu

validates :content, presence: { message: "le contenu doit être renseigné."}
validates :content, length: {minimum: 20, message: "Le contenu doit faire au moins 20 caracteres"}


end

app/models/message_prive.rb
class MessagePrive < ApplicationRecord
	#je permet une relation sender et recipient avec la class user
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	#cette relation: un tag peut avoir plusieur gossip
	has_many :tagGossips
	has_many :Gossips, through: :tagGossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	#cette relation intermédiaire me permet de faire le lien entre gossip et tag
	belongs_to :gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	#j'effectue ma relation: 1 utilisateur appartient à 1 ville
	belongs_to :city
	#l'utilisateur peut avoir écrit plusieur gossips
	has_many :gossips
	#qu'un user peut envoyer plusieur message et recevoir plusieur message
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "MessagePrive"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "MessagePrive"
	#un user peut écrire plusieur commentaires
	has_many :comments
	
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	validates :first_name, presence: {message: "Le prenom doit être renseigné !"}
	validates :last_name, presence:  {message: "Le nom doit être renseigné !"}
	validates :description, presence: {message: "La description doit être renseigné !"}
	validates :email, uniqueness: {message: "l'email est deja pris !"}
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "L'email doit être renseigné au bon format (email@eamil.email) !"}
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/team_page_helper.rb
module TeamPageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <!-- NavBar --!>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" <%= link_to "THP - Montpellier", gossips_path %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Team", team_path %></a>
          </li>
          <li class="nav-item">
        <a class="nav-link" <%= link_to "Contact", contact_path %></a>
          </li>
        </ul>
        <% if current_user %>
        <a class="nav-link" <%= link_to "Mon profil", author_path(session[:user_id]) %></a>
        <a class="nav-link" <%= link_to "Deconnexion", session_path(session.id), method: :delete %></a>
        <% else %>
        <a class="nav-link" <%= link_to "Connexion", new_session_path %></a>
        <a class="nav-link" <%= link_to "S'inscrire", new_author_path %></a>
        <% end %>
      </div>
    </nav>


    <%= yield %>
  </body>
</html>